[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.81.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.81.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
  from = "/login/"
  to = "https://frontend-mudmap-01.netlify.app/"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://mudmap.co/api/:splat 200
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "https://mudmap.co/admin/:splat 200
  status = 200

[[redirects]]
  from = "/static/*"
  to = "https://mudmap.co/static/:splat 200
  status = 200
